// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using addon365.Database;

namespace addon365.Database.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("addon")
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("addon365.Database.Entity.Accounts.AccountBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookName");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ProgrammerId");

                    b.Property<Guid>("UnderGroupId");

                    b.HasKey("Id");

                    b.ToTable("AccountBooks");
                });

            modelBuilder.Entity("addon365.Database.Entity.Accounts.PaymentMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<string>("ProgrammerId");

                    b.HasKey("Id");

                    b.ToTable("PaymentModes");
                });

            modelBuilder.Entity("addon365.Database.Entity.Accounts.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<DateTime>("VoucherDate");

                    b.Property<Guid>("VoucherTypeId");

                    b.HasKey("Id");

                    b.HasIndex("VoucherTypeId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("addon365.Database.Entity.Accounts.VoucherInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("FieldInfo");

                    b.Property<bool>("IsCredit");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("VoucherId");

                    b.Property<Guid>("bookId");

                    b.HasKey("Id");

                    b.HasIndex("VoucherId");

                    b.HasIndex("bookId");

                    b.ToTable("VouchersInfo");
                });

            modelBuilder.Entity("addon365.Database.Entity.Accounts.VoucherTypeMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("ParentId");

                    b.Property<string>("ProgrammerId");

                    b.HasKey("Id");

                    b.ToTable("VoucherTypeMasters");
                });

            modelBuilder.Entity("addon365.Database.Entity.BranchMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<string>("BranchName");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid>("LicenseMasterId");

                    b.Property<string>("Location");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ShortCode");

                    b.HasKey("Id");

                    b.ToTable("BranchMasters");
                });

            modelBuilder.Entity("addon365.Database.Entity.Chit.ChitScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BonusAmount");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<double>("FinalBonus");

                    b.Property<bool>("HasFixedDate");

                    b.Property<int>("MaxMembers");

                    b.Property<DateTime>("Modified");

                    b.Property<double>("MonthlyAmount");

                    b.Property<string>("SchemaName");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("TotalMonths");

                    b.HasKey("Id");

                    b.ToTable("ChitSchemes");
                });

            modelBuilder.Entity("addon365.Database.Entity.Chit.ChitSubriberDue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("ChitSubscriberId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("DueNo")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("VoucherId");

                    b.HasKey("Id");

                    b.HasIndex("ChitSubscriberId");

                    b.HasIndex("VoucherId");

                    b.ToTable("ChitSubscriberDues");
                });

            modelBuilder.Entity("addon365.Database.Entity.Chit.ChitSubscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("ChitSchemeId");

                    b.Property<Guid>("ClosedVoucherId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<Guid>("CustomerId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("JoinedDate");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("SubscribeId");

                    b.HasKey("Id");

                    b.HasIndex("ChitSchemeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ChitSubscribers");
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.AddressMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid?>("CountryId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("DistrictId");

                    b.Property<string>("LocalityOrVillage");

                    b.Property<Guid?>("LocalityOrVillageId");

                    b.Property<DateTime>("Modified");

                    b.Property<long>("PinOrZip");

                    b.Property<Guid?>("StateId");

                    b.Property<string>("SubDistrict");

                    b.Property<Guid?>("SubDistrictId");

                    b.HasKey("Id");

                    b.ToTable("AddressMaster");
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.BusinessContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<string>("BusinessName");

                    b.Property<Guid?>("ContactAddressId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Landline");

                    b.Property<string>("MobileNumber");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("SecondaryMobileNo");

                    b.HasKey("Id");

                    b.HasIndex("ContactAddressId");

                    b.ToTable("BusinessContact");
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Filter");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.CampaignInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("CampaignId");

                    b.Property<string>("Comments");

                    b.Property<Guid>("ContactId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid>("ModeId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("ModeId");

                    b.HasIndex("StatusId");

                    b.ToTable("CampaignInfos");
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<Guid?>("AddressId");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid?>("ContactAddressId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("FirstName");

                    b.Property<string>("Identifier");

                    b.Property<string>("LastName");

                    b.Property<string>("MobileNumber");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Place");

                    b.Property<string>("SecondaryMobileNo");

                    b.HasKey("Id");

                    b.HasIndex("ContactAddressId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ProfileId");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.FollowUpMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Description");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FollowUpModes");
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.FollowUpStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Description");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FollowUpStatuses");
                });

            modelBuilder.Entity("addon365.Database.Entity.DeviceMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("DeviceId");

                    b.Property<string>("DeviceName");

                    b.Property<string>("MacId1");

                    b.Property<string>("MacId2");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("OtherId");

                    b.HasKey("Id");

                    b.ToTable("DeviceMasters");
                });

            modelBuilder.Entity("addon365.Database.Entity.Employee.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("ContactId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("DepartmentId");

                    b.Property<Guid?>("DesignationId");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("JoiningDate");

                    b.Property<DateTime>("LastDate");

                    b.Property<DateTime>("Modified");

                    b.Property<double>("Salary");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.Enquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("ContactId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("EnquiryDate");

                    b.Property<Guid>("EnquiryTypeId");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("StatusId");

                    b.Property<Guid?>("VoucherId");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("EnquiryTypeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.EnquiryAccessories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccessoriesId");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("CatalogItemId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid>("EnquiryId");

                    b.Property<DateTime>("Modified");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("EnquiryId");

                    b.ToTable("EnquiryAccessories");
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.EnquiryExchangeQuotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid>("EnquiryId");

                    b.Property<double>("ExpectedAmount");

                    b.Property<string>("Model");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NoOfOwner");

                    b.Property<double>("QuotatedAmount");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("EnquiryId");

                    b.ToTable("EnquiryExchangeQuotations");
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.EnquiryFinanceQuotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid>("EnquiryProductId");

                    b.Property<double>("InitialDownPayment");

                    b.Property<DateTime>("Modified");

                    b.Property<double>("MonthlyEMIAmount");

                    b.Property<int>("NumberOfMonths");

                    b.HasKey("Id");

                    b.HasIndex("EnquiryProductId");

                    b.ToTable("EnquiryFinanceQuotations");
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.EnquiryProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AccessoriesAmount");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("CatalogItemId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid>("EnquiryId");

                    b.Property<DateTime>("Modified");

                    b.Property<double>("OnRoadPrice");

                    b.Property<double>("OtherAmount");

                    b.Property<double>("TotalAmount");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("EnquiryId");

                    b.ToTable("EnquiryProducts");
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.EnquiryStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int>("ProgrammerId");

                    b.HasKey("Id");

                    b.ToTable("EnquiryStatuses");
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.EnquiryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ProgrammerId");

                    b.HasKey("Id");

                    b.ToTable("EnquriyType");
                });

            modelBuilder.Entity("addon365.Database.Entity.Finance.FinanceCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FinanceCompanies");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Buyer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("BusinessContactId");

                    b.Property<string>("BuyerId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BusinessContactId");

                    b.ToTable("Inventory.Buyers");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Catalog.CatalogBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<string>("CompanyName");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("ProgrammerID");

                    b.HasKey("Id");

                    b.ToTable("Inventory.Catalog.CatalogBrands");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Catalog.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("CompanyId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<double>("GST");

                    b.Property<string>("HSN");

                    b.Property<string>("Identifier");

                    b.Property<double>("InsuranceAmount");

                    b.Property<string>("ItemName");

                    b.Property<DateTime>("Modified");

                    b.Property<double>("Price");

                    b.Property<double>("RoadTax");

                    b.Property<Guid>("TypeId");

                    b.HasKey("Id");

                    b.ToTable("Inventory.Catalog.CatalogItems");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Catalog.CatalogItemPropertiesMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CatalogItemId");

                    b.Property<Guid>("CatalogPropertyMasterId");

                    b.Property<int>("ValueType");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("CatalogPropertyMasterId");

                    b.ToTable("Inventory.Catalog.CatalogItemPropertiesMaps");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Catalog.CatalogItemPropertyMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("PropertyName");

                    b.HasKey("Id");

                    b.ToTable("Inventory.Catalog.CatalogItemPropertyMasters");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Catalog.CatalogType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<Guid>("ParentId");

                    b.Property<int>("ProgrammerId");

                    b.HasKey("Id");

                    b.ToTable("Inventory.Catalog.CatalogTypes");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Purchases.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<DateTime>("InvoiceDate");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("PurchaseInvoiceNo");

                    b.Property<Guid>("SellerId");

                    b.Property<Guid?>("VoucherId");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Inventory.Purchases.Purchases");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Purchases.PurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("CatalogItemId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<decimal>("Price");

                    b.Property<Guid>("PurchaseId");

                    b.Property<decimal>("Unit");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("Inventory.Purchases.PurchasesItems");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Purchases.PurchaseItemPropertyMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("PurchaseItemId");

                    b.Property<decimal>("Unit");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseItemId");

                    b.ToTable("Inventory.Purchases.PurchasesItemsPropertiesMaps");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Purchases.PurchaseItemPropertyValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CatalogPropertyMasterId");

                    b.Property<Guid>("PurchaseItemPropertyMapId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CatalogPropertyMasterId");

                    b.HasIndex("PurchaseItemPropertyMapId");

                    b.ToTable("Inventory.Purchases.PurchasesItemsPropertiesValues");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BillDate");

                    b.Property<string>("BillNo");

                    b.Property<Guid?>("BillingAddressId");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("BuyerId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<Guid>("CustomerId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ShippingAddressId");

                    b.Property<Guid>("VoucherId");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Inventory.Sales.Sales");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Sales.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("CatalogItemId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<decimal>("Price");

                    b.Property<double>("Quantity");

                    b.Property<Guid?>("SaleId");

                    b.Property<Guid>("SalesId");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("SaleId");

                    b.ToTable("Inventory.Sales.SalesItems");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Sales.SaleItemProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("GroupId");

                    b.Property<Guid>("ProductPropertyMasterId");

                    b.Property<Guid?>("SaleItemId");

                    b.Property<Guid>("SalesItemsId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("SaleItemId");

                    b.ToTable("Inventory.Sales.SalesItemsProperties");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("BusinessContactId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("SellerId");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BusinessContactId");

                    b.ToTable("Inventory.Sellers");
                });

            modelBuilder.Entity("addon365.Database.Entity.LicenseMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<string>("BusinessName");

                    b.Property<Guid>("CatalogItemId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<Guid>("CustomerId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid>("LicenseId");

                    b.Property<string>("Location");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("URL");

                    b.Property<Guid>("VoucherId");

                    b.HasKey("Id");

                    b.ToTable("LicenseMasters");
                });

            modelBuilder.Entity("addon365.Database.Entity.MarketingZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ZonalDescription");

                    b.Property<string>("ZonalName");

                    b.HasKey("Id");

                    b.ToTable("marketingZones");
                });

            modelBuilder.Entity("addon365.Database.Entity.Report.InquiryReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("InquiryReport");
                });

            modelBuilder.Entity("addon365.Database.Entity.Threats.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("addon365.Database.Entity.Threats.Threat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Host");

                    b.Property<string>("Identifier")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CONCAT('SVB-',[Id])");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Protocol");

                    b.Property<string>("QueryString");

                    b.Property<string>("Referer")
                        .HasMaxLength(255);

                    b.Property<Guid>("StatusId");

                    b.Property<Guid>("TypeId");

                    b.Property<string>("UserAgent");

                    b.Property<string>("XForwardHost");

                    b.Property<string>("XForwardProto");

                    b.HasKey("Id");

                    b.HasIndex("Referer")
                        .IsUnique()
                        .HasFilter("[Referer] IS NOT NULL");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("Threats");
                });

            modelBuilder.Entity("addon365.Database.Entity.Threats.ThreatType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("CreatedDeviceId");

                    b.Property<int?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("addon365.Database.Entity.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmPassword");

                    b.Property<int>("OtherId");

                    b.Property<string>("Password");

                    b.Property<string>("SessionToken");

                    b.Property<string>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("addon365.Database.Entity.Accounts.Voucher", b =>
                {
                    b.HasOne("addon365.Database.Entity.Accounts.VoucherTypeMaster", "VoucherTypeMaster")
                        .WithMany()
                        .HasForeignKey("VoucherTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Accounts.VoucherInfo", b =>
                {
                    b.HasOne("addon365.Database.Entity.Accounts.Voucher")
                        .WithMany("VoucherInfos")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Accounts.AccountBook", "AccountBook")
                        .WithMany()
                        .HasForeignKey("bookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Chit.ChitSubriberDue", b =>
                {
                    b.HasOne("addon365.Database.Entity.Chit.ChitSubscriber", "ChitSubscriber")
                        .WithMany()
                        .HasForeignKey("ChitSubscriberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Accounts.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId");
                });

            modelBuilder.Entity("addon365.Database.Entity.Chit.ChitSubscriber", b =>
                {
                    b.HasOne("addon365.Database.Entity.Chit.ChitScheme", "ChitSchema")
                        .WithMany()
                        .HasForeignKey("ChitSchemeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Crm.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.BusinessContact", b =>
                {
                    b.HasOne("addon365.Database.Entity.Crm.AddressMaster", "ContactAddress")
                        .WithMany()
                        .HasForeignKey("ContactAddressId");
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.CampaignInfo", b =>
                {
                    b.HasOne("addon365.Database.Entity.Crm.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Crm.FollowUpMode", "Mode")
                        .WithMany()
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Crm.FollowUpStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.Contact", b =>
                {
                    b.HasOne("addon365.Database.Entity.Crm.AddressMaster", "ContactAddress")
                        .WithMany()
                        .HasForeignKey("ContactAddressId");
                });

            modelBuilder.Entity("addon365.Database.Entity.Crm.Customer", b =>
                {
                    b.HasOne("addon365.Database.Entity.Crm.Contact", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("addon365.Database.Entity.Employee.Employee", b =>
                {
                    b.HasOne("addon365.Database.Entity.Crm.Contact", "Profile")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.Enquiry", b =>
                {
                    b.HasOne("addon365.Database.Entity.Crm.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Enquiries.EnquiryType", "EnquiryType")
                        .WithMany()
                        .HasForeignKey("EnquiryTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Enquiries.EnquiryStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Accounts.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId");
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.EnquiryAccessories", b =>
                {
                    b.HasOne("addon365.Database.Entity.Inventory.Catalog.CatalogItem", "product")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Enquiries.Enquiry", "enquiry")
                        .WithMany()
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.EnquiryExchangeQuotation", b =>
                {
                    b.HasOne("addon365.Database.Entity.Enquiries.Enquiry")
                        .WithMany("EnquiryExchangeQuotations")
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.EnquiryFinanceQuotation", b =>
                {
                    b.HasOne("addon365.Database.Entity.Enquiries.EnquiryProduct")
                        .WithMany("EnquiryFinanceQuotations")
                        .HasForeignKey("EnquiryProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Enquiries.EnquiryProduct", b =>
                {
                    b.HasOne("addon365.Database.Entity.Inventory.Catalog.CatalogItem", "Product")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Enquiries.Enquiry")
                        .WithMany("EnquiryProducts")
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Buyer", b =>
                {
                    b.HasOne("addon365.Database.Entity.Crm.BusinessContact", "BusinessContact")
                        .WithMany()
                        .HasForeignKey("BusinessContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Catalog.CatalogItemPropertiesMap", b =>
                {
                    b.HasOne("addon365.Database.Entity.Inventory.Catalog.CatalogItem")
                        .WithMany("Properties")
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Inventory.Catalog.CatalogItemPropertyMaster", "PropertyMaster")
                        .WithMany()
                        .HasForeignKey("CatalogPropertyMasterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Purchases.Purchase", b =>
                {
                    b.HasOne("addon365.Database.Entity.Inventory.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Accounts.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Purchases.PurchaseItem", b =>
                {
                    b.HasOne("addon365.Database.Entity.Inventory.Catalog.CatalogItem", "Product")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Inventory.Purchases.Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Purchases.PurchaseItemPropertyMap", b =>
                {
                    b.HasOne("addon365.Database.Entity.Inventory.Purchases.PurchaseItem", "PurchaseItem")
                        .WithMany("ItemPropertyMaps")
                        .HasForeignKey("PurchaseItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Purchases.PurchaseItemPropertyValue", b =>
                {
                    b.HasOne("addon365.Database.Entity.Inventory.Catalog.CatalogItemPropertyMaster", "CatalogItemPropertyMaster")
                        .WithMany()
                        .HasForeignKey("CatalogPropertyMasterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Inventory.Purchases.PurchaseItemPropertyMap")
                        .WithMany("PropertyValues")
                        .HasForeignKey("PurchaseItemPropertyMapId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Sales.Sale", b =>
                {
                    b.HasOne("addon365.Database.Entity.Inventory.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Crm.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Accounts.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Sales.SaleItem", b =>
                {
                    b.HasOne("addon365.Database.Entity.Inventory.Catalog.CatalogItem", "Product")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Inventory.Sales.Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Sales.SaleItemProperty", b =>
                {
                    b.HasOne("addon365.Database.Entity.Inventory.Sales.SaleItem")
                        .WithMany("Properties")
                        .HasForeignKey("SaleItemId");
                });

            modelBuilder.Entity("addon365.Database.Entity.Inventory.Seller", b =>
                {
                    b.HasOne("addon365.Database.Entity.Crm.BusinessContact", "BusinessContact")
                        .WithMany()
                        .HasForeignKey("BusinessContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("addon365.Database.Entity.Threats.Threat", b =>
                {
                    b.HasOne("addon365.Database.Entity.Threats.Status", "Status")
                        .WithMany("Threats")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("addon365.Database.Entity.Threats.ThreatType", "ThreatType")
                        .WithMany("Threats")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
