// <auto-generated />
using System;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Database.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20181129051129_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("swc")
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api.Database.Entity.Accounts.PaymentMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<string>("ProgrammerId");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("PaymentModes");
                });

            modelBuilder.Entity("Api.Database.Entity.Accounts.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Api.Database.Entity.Accounts.VoucherInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<Guid>("BookId");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<string>("FieldInfo");

                    b.Property<bool>("IsCredit");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("VoucherId");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("VouchersInfo");
                });

            modelBuilder.Entity("Api.Database.Entity.BranchMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<string>("BranchName");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<Guid>("LicenseId");

                    b.Property<string>("Location");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("ProgrammerID");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("BranchMaster");
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<string>("Filter");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.CampaignInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("CampaignId");

                    b.Property<string>("Comments");

                    b.Property<Guid>("ContactId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<Guid>("ModeId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.HasIndex("ContactId");

                    b.HasIndex("ModeId");

                    b.HasIndex("StatusId");

                    b.ToTable("CampaignInfos");
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<string>("Identifier");

                    b.Property<string>("MobileNumber");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<string>("Place");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("ContactId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.HasIndex("ContactId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.FollowUpMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Description");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("FollowUpModes");
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.FollowUpStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Description");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("FollowUpStatuses");
                });

            modelBuilder.Entity("Api.Database.Entity.Employee.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid?>("BranchMasterId1");

                    b.Property<Guid>("ContactId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("DepartmentId");

                    b.Property<Guid?>("DesignationId");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("JoiningDate");

                    b.Property<DateTime>("LastDate");

                    b.Property<DateTime>("Modified");

                    b.Property<double>("Salary");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId1");

                    b.HasIndex("ContactId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.Enquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("ContactId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("EnquiryDate");

                    b.Property<Guid>("EnquiryTypeId");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("StatusId");

                    b.Property<Guid>("VoucherId");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.HasIndex("ContactId");

                    b.HasIndex("EnquiryTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryAccessories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccessoriesId");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<Guid>("EnquiryId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.HasIndex("EnquiryId");

                    b.HasIndex("ProductId");

                    b.ToTable("EnquiryAccessories");
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryExchangeQuotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<Guid>("EnquiryId");

                    b.Property<double>("ExpectedAmount");

                    b.Property<string>("Model");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NoOfOwner");

                    b.Property<double>("QuotatedAmount");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.HasIndex("EnquiryId");

                    b.ToTable("EnquiryExchangeQuotations");
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryFinanceQuotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<Guid>("EnquiryProductId");

                    b.Property<double>("InitialDownPayment");

                    b.Property<DateTime>("Modified");

                    b.Property<double>("MonthlyEMIAmount");

                    b.Property<int>("NumberOfMonths");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.HasIndex("EnquiryProductId");

                    b.ToTable("EnquiryFinanceQuotations");
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AccessoriesAmount");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<Guid>("EnquiryId");

                    b.Property<DateTime>("Modified");

                    b.Property<double>("OnRoadPrice");

                    b.Property<double>("OtherAmount");

                    b.Property<Guid>("ProductId");

                    b.Property<double>("TotalAmount");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.HasIndex("EnquiryId");

                    b.HasIndex("ProductId");

                    b.ToTable("EnquiryProducts");
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int>("ProgrammerId");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("EnquiryStatuses");
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ProgrammerId");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("EnquriyType");
                });

            modelBuilder.Entity("Api.Database.Entity.Finance.FinanceCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("FinanceCompanies");
                });

            modelBuilder.Entity("Api.Database.Entity.Inventory.InventoryInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<double>("Discount");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<Guid>("InventoryItemMasterId");

                    b.Property<Guid>("InventoryMasterId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("ProductId");

                    b.Property<double>("Unit");

                    b.Property<double>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("InventoryInfos");
                });

            modelBuilder.Entity("Api.Database.Entity.Inventory.InventoryItemMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<string>("ChasisNo");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("InventoryItemMasters");
                });

            modelBuilder.Entity("Api.Database.Entity.Inventory.InventoryMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<Guid>("CustomerId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.HasIndex("CustomerId");

                    b.ToTable("InventoryMasters");
                });

            modelBuilder.Entity("Api.Database.Entity.LicenseMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BusinessName");

                    b.Property<string>("LicenseId");

                    b.Property<string>("Location");

                    b.Property<int>("ProgrammerID");

                    b.HasKey("Id");

                    b.ToTable("LicenseMasters");
                });

            modelBuilder.Entity("Api.Database.Entity.MarketingZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ZonalDescription");

                    b.Property<string>("ZonalName");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("marketingZones");
                });

            modelBuilder.Entity("Api.Database.Entity.Products.ExtraFittingsAccessories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccessoriesProductId");

                    b.Property<Guid?>("AccessoriesProductItemId");

                    b.Property<double>("Amount");

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid>("ProductId");

                    b.Property<double>("Unit");

                    b.Property<double>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("AccessoriesProductItemId");

                    b.HasIndex("BranchMasterId");

                    b.HasIndex("ProductId");

                    b.ToTable("ExtraFittings");
                });

            modelBuilder.Entity("Api.Database.Entity.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<Guid>("CompanyId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<double>("GST");

                    b.Property<string>("HSN");

                    b.Property<string>("Identifier");

                    b.Property<double>("InsuranceAmount");

                    b.Property<DateTime>("Modified");

                    b.Property<double>("Price");

                    b.Property<string>("ProductName");

                    b.Property<double>("RoadTax");

                    b.Property<Guid>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Api.Database.Entity.Products.ProductCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<string>("CompanyName");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("ProgrammerID");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("ProductCompanies");
                });

            modelBuilder.Entity("Api.Database.Entity.Products.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<string>("Identifier");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<Guid>("ParentId");

                    b.Property<int>("ProgrammerId");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("Api.Database.Entity.Report.InquiredMonthly", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MonthIndex");

                    b.Property<int>("ProductCount");

                    b.Property<string>("ProductName");

                    b.HasKey("Id");

                    b.ToTable("InquiredProducts");
                });

            modelBuilder.Entity("Api.Database.Entity.Threats.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Api.Database.Entity.Threats.Threat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<string>("Host");

                    b.Property<string>("Identifier")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CONCAT('swc-',[Id])");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Protocol");

                    b.Property<string>("QueryString");

                    b.Property<string>("Referer")
                        .HasMaxLength(255);

                    b.Property<Guid>("StatusId");

                    b.Property<Guid>("TypeId");

                    b.Property<string>("UserAgent");

                    b.Property<string>("XForwardHost");

                    b.Property<string>("XForwardProto");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.HasIndex("Referer")
                        .IsUnique()
                        .HasFilter("[Referer] IS NOT NULL");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("Threats");
                });

            modelBuilder.Entity("Api.Database.Entity.Threats.ThreatType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("Api.Database.Entity.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BranchMasterId");

                    b.Property<string>("ConfirmPassword");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedDeviceId");

                    b.Property<Guid?>("CreatedUserId");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Password");

                    b.Property<string>("SessionToken");

                    b.Property<string>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Database.Entity.Accounts.PaymentMode", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Accounts.Voucher", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Accounts.VoucherInfo", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.BranchMaster", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.Campaign", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.CampaignInfo", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");

                    b.HasOne("Api.Database.Entity.Crm.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Database.Entity.Crm.FollowUpMode", "Mode")
                        .WithMany()
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Database.Entity.Crm.FollowUpStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.Contact", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.Customer", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");

                    b.HasOne("Api.Database.Entity.Crm.Contact", "Profile")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.FollowUpMode", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Crm.FollowUpStatus", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Employee.Employee", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId1");

                    b.HasOne("Api.Database.Entity.Crm.Contact", "Profile")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.Enquiry", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");

                    b.HasOne("Api.Database.Entity.Crm.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Database.Entity.Enquiries.EnquiryType", "EnquiryType")
                        .WithMany("Enquiries")
                        .HasForeignKey("EnquiryTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Database.Entity.Enquiries.EnquiryStatus", "Status")
                        .WithMany("Enquiries")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryAccessories", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");

                    b.HasOne("Api.Database.Entity.Enquiries.Enquiry", "enquiry")
                        .WithMany()
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Database.Entity.Products.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryExchangeQuotation", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");

                    b.HasOne("Api.Database.Entity.Enquiries.Enquiry", "enquiry")
                        .WithMany()
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryFinanceQuotation", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");

                    b.HasOne("Api.Database.Entity.Enquiries.EnquiryProduct", "enquiryProduct")
                        .WithMany()
                        .HasForeignKey("EnquiryProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryProduct", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");

                    b.HasOne("Api.Database.Entity.Enquiries.Enquiry", "Enquiry")
                        .WithMany("EnquiryProducts")
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Database.Entity.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryStatus", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Enquiries.EnquiryType", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Finance.FinanceCompany", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Inventory.InventoryInfo", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Inventory.InventoryItemMaster", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Inventory.InventoryMaster", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");

                    b.HasOne("Api.Database.Entity.Crm.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Database.Entity.MarketingZone", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Products.ExtraFittingsAccessories", b =>
                {
                    b.HasOne("Api.Database.Entity.Products.Product", "AccessoriesProductItem")
                        .WithMany()
                        .HasForeignKey("AccessoriesProductItemId");

                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");

                    b.HasOne("Api.Database.Entity.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Database.Entity.Products.Product", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Products.ProductCompany", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Products.ProductType", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Threats.Status", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.Threats.Threat", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");

                    b.HasOne("Api.Database.Entity.Threats.Status", "Status")
                        .WithMany("Threats")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Database.Entity.Threats.ThreatType", "ThreatType")
                        .WithMany("Threats")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Database.Entity.Threats.ThreatType", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("Api.Database.Entity.User.User", b =>
                {
                    b.HasOne("Api.Database.Entity.BranchMaster", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });
#pragma warning restore 612, 618
        }
    }
}
